### ISSUE TITLE
Err] [InsertModelWidget.cc:402] Missing model.config for model 

### ISSUE THREAD

**Issue by laxnpander** [larics/icuas22_competition#2]
Hey,

when starting the simulation in a docker container using your provided instructions I run into the following error:
```
[Err] [InsertModelWidget.cc:402] Missing model.config for model "/root/uav_ws/src/larics_gazebo_worlds/../icuas22_competition"
[Err] [InsertModelWidget.cc:402] Missing model.config for model "/root/uav_ws/src/larics_gazebo_worlds/../larics_gazebo_worlds"
[Err] [InsertModelWidget.cc:402] Missing model.config for model "/root/uav_ws/src/larics_gazebo_worlds/../uav_ros_simulation"
```

Any suggestions what might cause it?

Edit: Internet suggests to ignore it, but other nodes throw errors as well. Such as:
```
[ERROR] [1643800657.336116, 0.000000]: Spawn service failed. Exiting.
```
by the spawn robot. Is it safe to ignore that as well? Seems like the multicopter is spawning and running.

**Comment by lmark1** [comment]
The simulation should behave correctly despite this error. Gazebo complains if model metadata is not present for each model.

**Comment by laxnpander** [comment]
@lmark1: Alright, thanks! Then it looks like everything is working as intended!
