### ISSUE TITLE
Current UAV Pose Topic

### ISSUE THREAD

**Issue by EceChaik** [larics/icuas22_competition#28]
Hi,

I have a question regarding the topic at which the UAV's current pose should be available.
Currently it is mentioned in the instructions that this should be **mavros/global_position/local**, however I think this topic might no be updated with position estimates at this point. 
The UAV's pose **is** accurately tracked by the **/red/odometry** topic (presumably this is direct gazebo data) so I'm wondering if we can subscribe to that one instead.

**Comment by fpetric** [comment]
Hi @EceChaik, 

I guess we forgot to update the README after we switched from mavros to direct gazebo data on /red/odometry topic, so the answer is: yes, you can and should subsrcibe to /red/odometry topic (that is the topic that the controller uses).

We will update the README. Thanks for reporting!

**Comment by EceChaik** [comment]
Great, thanks!
