### ISSUE TITLE
Pose of registered depth

### ISSUE THREAD

**Issue by laxnpander** [larics/icuas22_competition#37]
Hey hey,

I currently wonder on what pose the registered depth of 
```
/red/camera/depth_registered/points
```
 is based on? I'd assume it is computed with some camera internal SLAM pose, not with the one from the external tracking system? 
If that is the case and one wants to use the tracking pose together with the depth map by the camera: Will we get a transformation camera -> uav frame?

Best regards,

Alex

**Comment by lmark1** [comment]
Hi @laxnpander,

The camera plugin is [gazebo_ros_openni_kinect](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/noetic-devel/gazebo_plugins/src/gazebo_ros_openni_kinect.cpp) which is a part of the standard gazebo ROS simulation packages.
I believe it's simply reading the depth from the Gazebo camera sensor and republishing it to a ROS topic. 

You can get the transformation from base_link to the camera via the ```/tf``` topic. 

Best regards,
Lovro

**Comment by laxnpander** [comment]
@lmark1 I see, thanks! And the ```/tf``` topic will be available in the "real" setup as well?

**Comment by laxnpander** [comment]
Perfect, all questions resolved!
