### ISSUE TITLE
Docker start.sh launch issue

### ISSUE THREAD

**Issue by afaroo01** [larics/icuas22_competition#47]
I am getting these issues whenever I run the docker and do start.sh. Please let me know what is causing this issue and how to resolve. Thanks

![277906968_1291793731328614_448800888391855217_n](https://user-images.githubusercontent.com/64008660/162562148-6cddf737-82b0-4db6-bb2a-49e2532d3a3e.jpg)

**Comment by lmark1** [comment]
Hello @afaroo01,

At the first glance it seems you are running an old base image of the UAV simulation stack.

The commands you need to run to start the challenge in Docker are as follows:
```bash
# pull the newest uav_ros_simulation image
docker pull lmark1/uav_ros_simulation:bionic

# navigate to icuas22_competition folder and pull newest changes
git pull origin main

# build the ICUAS challenge docker image
./docker_build.sh --bionic

# you might need to remove the old container if you previously ran it
docker container rm icuas22_competition_bionic

# run the challenge container
./docker_run.sh --bionic

# once in the container navigate to the startup/challenge folder and run start.sh
cd startup/challenge
./start.sh
```

From what I can tell the challenge runs fine on both bionic and focal distributions.

Please refer to the [README.md](https://github.com/larics/icuas22_competition/blob/main/README.md) for more instructions and explanations about building and running the challenge simulation.

Best regards,
Lovro

**Comment by afaroo01** [comment]
Hi @lmark1 

Thanks for your reply. I was able to remove the previous errors by doing a fresh installation. However, now the ./start.sh only shows a ground-truth and spawn a red (uav) in the models of the gazebo as you can see. No arena, obstacles and ball are seen. Can you tell what is causing it not setting up the setup?

![IMG_20220411_172912](https://user-images.githubusercontent.com/64008660/162762320-c68b67ba-1d46-4695-88ad-eda10637d17b.jpg)

**Comment by afaroo01** [comment]
Hi @aivano  and @fpetric, might you can resolve this second issue. It's related to not seeing the arena ball and proper competition layout in gazebo after fresh installation of the setup using docker image.

**Comment by afaroo01** [comment]
@lmark1 @fpetric @aivano 
 
Regarding the lat comment. I checked in the gazebo terminal, is says waiting for simulation and nothing appears still. Can you please help out on this issue?

![IMG20220412154838](https://user-images.githubusercontent.com/64008660/162965977-ee78e861-4ee2-49a7-b654-ba27bff13068.jpg)

**Comment by afaroo01** [comment]
The issue was resolved by running the following command in the icuas22_compeititon folder and building again. 

git pull origin main

**Comment by fpetric** [comment]
Sorry for not replying sooner, busy day :) glad you got it sorted out!
